name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git remote add huggingface https://ssbb2026:${HF_TOKEN}@huggingface.co/spaces/ssbb2026/ImageText

          git push huggingface HEAD:main --force
